# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20141004_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='level',
            field=models.SmallIntegerField(choices=[(10, 'debug'), (20, 'info'), (25, 'success'), (30, 'warning'), (40, 'error')], verbose_name='Level'),
        ),
    ]
